package com.example.helscorp.stockmanagement.exceptions;

public enum ErrorCodes {

    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALID(1001),
    ARTICLE_ALREADY_IN_USE(1002),

    CATEGORY_NOT_FOUND(2000),
    CATEGORY_NOT_VALID(2001),
    CATEGORY_ALREADY_IN_USE(2002),

    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),

    COMMANDE_CLIENT_NOT_FOUND(4000),
    COMMANDE_CLIENT_NOT_VALID(4001),
    COMMANDE_CLIENT_NON_MODIFIABLE(4002),
    COMMANDE_CLIENT_ALREADY_IN_USE(4003),


    COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
    COMMANDE_FOURNISSEUR_NOT_VALID(5001),
    COMMANDE_FOURNISSEUR_NON_MODIFIABLE(5002),
    COMMANDE_FOURNISSEUR_ALREADY_IN_USE(5003),

    ENTREPRISE_NOT_FOUND(6000),
    ENTREPRISE_NOT_VALID(6001),

    FOURNISSEUR_NOT_FOUND(8000),
    FOURNISSEUR_NOT_VALID(8001),

    LIGNE_COMMANDE_FORNISSEUR_NOT_FOUND(9000),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(10000),

    MVT_STOCK_NOT_FOUND(11000),
    MVT_STOCK_NOT_VALID(11001),

    UTILISATEUR_NOT_FOUND(12000),
    UTILISATEUR_NOT_VALID(12001),
    UTILISATEUR_ALREADY_IN_USE(12002),
    UTILISATEUR_NOT_CHANGE_PASSWORD_OBJECT_NOT_VALID(12003),

    BAD_CREDENTIALS(12004),

    VENTE_NOT_FOUND(16000),
    VENTE_NOT_VALID(16001),
    VENTE_ALREADY_IN_USE(16002),


    ;

    private int code;

    ErrorCodes(int theCode){
        this.code = theCode;
    }

    public int getCode(){
        return this.code;
    }


}
